name: Deploy to WP Engine PRD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ secrets.ENV_PRD }}
          SRC_PATH: '.'                # Optional, default is '.'
          REMOTE_PATH: '/wp-content/themes/'  # Set to your theme path
          CACHE_CLEAR: true            # Optional
